### ISSUE TITLE
As a user, I want to add pictures so that I can track my lifestyle.

### ISSUE THREAD

**Issue by amneet270** [admin341/INSTA341#6]
**Task Breakdown**
- User can only post a picture that is in following format: JPG, TIF or PNG. (2)
- Fix layout and resize picture to fit layout of post and picture. (1)
- Picture posted should be clickable with a mouse. (1)

**Comment by instamine** [comment]
Reviewed:
-Changed milestone from 1 to 2
-Deleted wrong description and restated the proper utility.

**Comment by vithura14** [comment]
This issue has already been taken care by the backend team.

**Comment by nuzurie** [comment]
As referenced, this feature was implemented on the post_pictures branch which has been merged. Doesn't have a pleasant user interface yet, but that can be done in the frontend branch. Since this was the first feature implemented, only based on user identity, the **RISK** value attributed would be **TWO** with no clash among features expected.
